#If this file is garbled, the problem is most likely due to character encoding.
#This file is written in utf - 8, and can be read by installing VS Code and configuring it to automatically detect the character encoding.
#This file is written in the TOML format. Just google it and you'll find easy to understand information on the wiki, so try looking it up.
#This file is a file for describing program settings.
#This file can also be edited with a text editor such as Notepad.
#If you want to change the simulation conditions, try changing them from here.Lines starting with a sharp are comments. They do not affect the program.Following description is written in Japanese. 
#
#このファイルが文字化けしている場合は，文字コードの問題が考えられます．
#このファイルはutf-8で記述されており，VS Codeをインストールし，文字コードを自動で検出するように設定することで読み込むことができます．
#このファイルはTOML形式で記述されています．ググればwikiに分かりやすい情報が載っているので，調べてみてください．
#このファイルはプログラムの設定を記述するファイルです．
#このファイルはメモ帳などのテキストエディタでも編集することができます．
#シミュレーション条件を変更したい場合は，ここから変更してみてください．
#シャープから始まる行はコメントです．プログラムに影響を与えることはありません．


#プログラムの起動モードの設定です
[Mode]
    
    #起動時に実行モードについて質問をするようにします．( true / false )
    ask_about_modes = true
    
    #起動時のデフォルトの実行モードを設定します．( "kSimulation" / "kViewer" / "kDisplayTest" / "kResultViewer" )
    default_mode = "kSimulation"
    
    #1動作ごとにステップ実行をするかどうかを設定します．( true / false )
    do_step_execution_each_gait = false
    
    #1シミュレーションごとにステップ実行をするかどうかを設定します．( true / false )
    do_step_execution_each_simulation = true
    
#プログラムの出力の設定です
[Output]
    
    #コマンドラインに出力する際，どこまで許可するかを設定します．( "kSystem" / "kError" / "kWarning" / "kInfo" / "kDebug" )
    cmd_output_detail = "kSystem" 
    
    #コマンドラインに出力するかどうかを設定します．( true / false )
    do_cmd_output = true
    
    #GUIを表示するかどうかを設定します．( true / false )
    do_gui_display = true
    
    #GUIを表示する際，どこまで許可するかを設定します．( "kLow" / "kMedium" / "kHigh" )
    gui_display_quality = "kHigh" 
    
    #グラフィカルウィンドウのFPSを設定します．15 ～ 60の範囲．推奨値は60です．
    window_fps = 60
    
    #グラフィカルウィンドウの横幅を設定します．512 ～ 1920の範囲．推奨値は1600です．
    window_size_x = 1600
    
    #グラフィカルウィンドウの縦幅を設定します．288 ～ 1080の範囲．推奨値は900です．
    window_size_y = 900
    
#ver major.minor.patch の順で記述されます．特に使う予定はないデータだけれど一応用意しておく．
[Verion]
    
    #メジャーバージョンは大きな更新があったときに変えます．
    version_major = 0
    version_minor = 5
    version_patch = 0
    
